### ISSUE TITLE
Port Qt WebEngine module

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qt5-os2#10]
This is a very huge task and this ticket will act as a meta ticket to some extent.

Besides the Qt WebEngine module, the following ones need to be also ported:

- [ ] qtwebengine-chromium (a submodule of `qtwebengine` rooted at `src/3rdparty`)
- [x] qtwebsockets
- [x] qtwebchannel

All these need OS/2 clones using the usual squash scheme since we may have our own patches.

**Comment by dmik** [comment]
BTW, Qt WebEngine needs various tools such as flex, bison and gperf. The first two we have, the last one (https://www.gnu.org/software/gperf/) we seem not to. Should be relatively easy to port.

**Comment by SilvanScherrer** [comment]
Gperf is in progress

**Comment by dmik** [comment]
Qt WebChannel and Qt WebSockets are done, I will run some tests now to make sure they work.

**Comment by dmik** [comment]
Fixed some problems with QML DLL names but there are still some test failures, created respective tickets (see above).

**Comment by martinrotter** [comment]
Guys, I am not even using OS/2, but I have to say one thing - your efforts are fu*king spectacular and I really admire your porting successes. Keep the work up!!

**Comment by dmik** [comment]
@martinrotter nevertheless, thank you!

**Comment by martinrotter** [comment]
@dmik Just a question, is there any ETA of then webengine could be available? I know it is horrific just to compile it, but just asking.

It would benefit [RSS Guard](https://github.com/martinrotter/rssguard) which was just ported to OS2 by me in cooperation with "Tellie" and transitively you I believe.

**Comment by dmik** [comment]
Congrats with that! Yes, I participated a tiny bit :) The WebEngie ETA is a good question. It's mostly ready, now we are working on its stability. Several weeks perhaps. And yes, compilation itself is an extreme task per se. Takes something like 15 hours with our tool chain IIRC.

**Comment by martinrotter** [comment]
@dmik Are there any yum/rpm packages to test?

**Comment by dmik** [comment]
Not as RPM. There is a test zip http://rpm.netlabs.org/test/qtwebtest5_4_pub.7z. You will need to install missing DLLs manually by checking the needed packages with `yum provides dllname` (dll name should be lower case).

**Comment by martinrotter** [comment]
I see, I will give this some time and will test after some weeks or maybe month, no hurry. Can you make some kind of announcement here when there is any progress?

**Comment by dmik** [comment]
Sure, it will be announced (as is all we release) here https://www.patreon.com/bwwbitwiseworks or here https://www.bitwiseworks.com/news/ or on any active OS/2 news site.

**Comment by dmik** [comment]
This should have been closed a few months ago — the Qt WebEngine module has been successfully ported and now we even updated it to version 5.15.2 (with the rest of Qt, see #16 for details).
