### ISSUE TITLE
QT5dbus

### ISSUE THREAD

**Issue by TeLLie** [bitwiseworks/qt5-os2#12]
Hi,
I notices that the Qtdbus port not fully is working.
A program i ported is using the QTdbus, its compiling but i cannot start the program, but when i disable the Qtdbus and recompile it's working.

As i understand we dont have a real backend yet.
I hope this would be fixed

**Comment by SilvanScherrer** [comment]
did you try with latest qt5?

**Comment by TeLLie** [comment]
Hi Silvan

I cannot find the programs that give trouble with it. I tried on a other
program and i dint notice any strange behavior..


Op ma 8 nov. 2021 12:44 schreef Silvan Scherrer ***@***.***>:
