### ISSUE TITLE
QT5WEB trap if using os4kernel  

### ISSUE THREAD

**Issue by GAnchieri** [bitwiseworks/qt5-os2#14]
I have installed, recently the last version of  QT5WEB, and it function in my pc with 
ARCAOS 506, but if I use OS4 KERNEL program trap immediately, is it a problem with the AVX instruction as in FFmpeg ?

I have two partition with ARCAOS 506 installed, one with a clean OS2 kernel and one with OS4 kernell to test.

Good work for now, I remain waiting for good news,
regards, 

I attach 2 files with the trap

G.M. Anchieri

**Comment by SilvanScherrer** [comment]
OS4 Kernel is not our main focus right now. After we have all stable as we wish, we might look into this issue. So dont expect a short solution.

**Comment by dryeo** [comment]
On 02/23/21 09:19 AM, GAnchieri wrote:
> but if I use OS4 KERNEL program trap immediately, is it a problem with
> the AVX instruction as in FFmpeg ?

There's a build of FFmpeg with AVX disabled posted here, 
https://www.os2world.com/forum/index.php/topic,2767.msg30680.html#msg30680

**Comment by dmik** [comment]
Please watch https://github.com/bitwiseworks/ffmpeg-os2/issues/5, we might release a new set of RPMs useful on CPUs with AVX enabled soon.
