### ISSUE TITLE
Port Qt Multimedia module

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qt5-os2#15]
This one is needed for the Otter browser. I guess it will mostly be a stub as we don't have easy-to-use driver-level support for things like camera support and 3D. And it's not really our top priority to have it. 

Reminders:
- [ ] Update README.md
- [ ] Update main Wiki page

**Comment by dryeo** [comment]
Should be mentioned that Wim has been working on webcam support, 
https://home.hccnet.nl/w.m.brul/usbvideo/index.html though as you say, 
low priority.

**Comment by dmik** [comment]
Qt Multimedia is imported and built with some minor corrections, see https://github.com/bitwiseworks/qtmultimedia-os2 for details. Now it's time to run some tests.

**Comment by dmik** [comment]
All tests now succeed (see https://github.com/bitwiseworks/qtmultimedia-os2/commit/7988e233ccdceb665fe81b59a20828cf6ee664f3 and previous ones).

Closing this ticket.
