### ISSUE TITLE
Are there "lrelease" and "lupdate" available?

### ISSUE THREAD

**Issue by martinrotter** [bitwiseworks/qt5-os2#5]
I installed qt5-* in my ArcaOS and "lrelease" and "lupdate" commands are not available in my shell. Are they even compiled in your binary packages?

Thanks for info in advance.

**Comment by SilvanScherrer** [comment]
those tools are not part of qtbase. They are in qttools. We will port qttools later on of course. So stay tuned for more stuff to come.

**Comment by dmik** [comment]
This is a sub-task of #6, closing. Please watch the main ticket for progress.
