### ISSUE TITLE
Qt5UiTools seems to be missing from qt5-qttools-devel

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/qt5-os2#9]
Trying to build zint, I am warned that qt5uitools-config.cmake cannot be found. A quick web search turns up that this (Qt5UiTools) should be part of the qt5-qttools-devel package, but it doesn't seem to be in there. I didn't report this a couple months ago when I first noticed, as I thought that perhaps it just hadn't been built yet, but after updating again tonight, I see that it's still not there.

**Comment by SilvanScherrer** [comment]
it seems you installed the wrong packages. qt5-devel you need. and this triggers a lot packages. including the one you search.
